BallotByIdTitle id@Text: Bulletin de vote n°#{id} - #OpElections
BallotFormTitle: Générateur de bulletins de vote - #OpElections
BallotListTitle: Liste des bulletins de vote - #OpElections
NotAuthorizedToDeleteBallot: Vous n'êtes pas authorisé à supprimer ce bulletin.
Generator host@Text: Ce vrai-faux bulletin de vote a été créé via http://#{host}/
ImageLoadFailed: Échec du chargement de l'image
NoBallotsYet: Oups, il n'y a aucun bulletin dans la base de données.
PostRateExceeded: Vous avez atteint la limite d'envois par jour.
SavedBallots i@Int: Vous avez sauvegardé #{show i} #{plural i "bulletin" "bulletins"}:
ShareOpelections url@Text: Votez contre le système, votez blanc ! #{url} %23opelections
