BallotByIdTitle id@Text: Bulletin n°#{id}
BallotFormTitle: Générateur de bulletins de vote
BallotListTitle: Liste des bulletins créés
NotAuthorizedToDeleteBallot: Vous n'êtes pas authorisé à supprimer ce bulletin.
Generator host@Text: Ce vrai-faux bulletin de vote a été créé via http://#{host}/
ImageLoadFailed: Échec du chargement de l'image
PostRateExceeded: Vous avez atteint la limite d'envois par jour.
SavedBallots i@Int: Vous avez sauvegardé #{show i} #{plural i "bulletin" "bulletins"}:
ShareText url@Text: Votez contre le système, votez blanc ! #opelections #{url}
ShareVoteUtile url@Text: Votez utile, votez blanc ! #{url}
