BallotByIdTitle id@Text: Bulletin de vote n°#{id} - #OpElections
BallotFormR: Générateur de bulletin
BallotFormTitle: Générateur de bulletins de vote - #OpElections
BallotListR: Liste des bulletins
BallotListTitle: Liste des bulletins de vote - #OpElections
NotAuthorizedToDeleteBallot: Vous n'êtes pas authorisé à supprimer ce bulletin.
Generator host@Text: Ce bulletin de vote a été créé via http://#{host}/
ImageLoadFailed: Échec du chargement de l'image
NoBallotsYet: Oups, il n'y a aucun bulletin dans la base de données.
PostRateExceeded: Vous avez atteint la limite d'envois par jour.
RootR: Accueil
SavedBallots i@Int: Vous avez sauvegardé #{show i} #{plural i "bulletin" "bulletins"}:
ShareBallot url@Text: J'adore ce bulletin de vote: #{url} %23opelections
ShareOpelections url@Text: Vous allez voter blanc aux élections ? Imprimez votre bulletin via #{url} %23opelections
ShareOwnBallot url@Text: Je viens de créer un bulletin de vote: #{url} %23opelections
