Default: &defaults
  host: "127.0.0.1"
  port: 8851
  approot: "//localhost:8851"

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "//opelections.oy.lc"
  <<: *defaults
