Default: &defaults
  database: opelections.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: opelections_test.sqlite3
  <<: *defaults

Staging:
  database: opelections_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ../../opelections_production.sqlite3
  poolsize: 100
  <<: *defaults
